### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by ScottDillman** [09th/Blender4Panda-loader#1]
I have been trying a bunch of scene exports from blender but always get the same error below. I am using the latest Blender4Panda-loader as well as the latest YABEE and Blender4Panda-plugin with Blender 2.74 AMD64 on both Windows and Ubuntu, Python 2.7.5 and Panda3D 1.9.0.. Using the following bit of code to load the scene:

``` python
from direct.showbase.ShowBase import ShowBase
from SceneLoader import Scene # SceneLoader is folder, with the Blender4Panda-loader content

base = ShowBase()
sc = Scene(render, loader, base) # pass root node for scene, loader and ShowBase object
sc.load('level.jsd') # load our .jsd file
sc.switch_camera() # Switch to the first camera if exist. You can comment this line and use default Panda's camera

base.run()
```

```
(all display modules loaded.)
('WARNING: unsupported uniform', {u'datatype': 2, u'varname': u'unf19', u'type': 21})
('WARNING: unsupported uniform', {u'datatype': 2, u'varname': u'unf20', u'type': 22})
('WARNING: unsupported uniform', {u'datatype': 2, u'varname': u'unf21', u'type': 23})
('WARNING: unsupported uniform', {u'datatype': 2, u'varname': u'unf22', u'type': 25})
('WARNING: unsupported uniform', {u'datatype': 2, u'varname': u'unf23', u'type': 24})
('WARNING: unsupported uniform', {u'datatype': 5, u'varname': u'unf27', u'type': 26})
--> ERROR while getting uniform: unf27 1
Traceback (most recent call last):
  File "load_level.py", line 6, in <module>
    sc.load('level.jsd') # load our .jsd file
  File "C:\work\SceneLoader\__init__.py", line 115, in load
    self.pass_through_ext('LOAD')
  File "C:\work\SceneLoader\__init__.py", line 100, in pass_through_ext
    ext.invoke(self, material, action)
  File "C:\work\\SceneLoader\ext\base_shader.py", line 43, in invoke
    get_unf_res = get_uniform(scene, unf)
  File "C:\work\SceneLoader\ext\shaders_conversion.py", line 440, in get_uniform
    raise exc
TypeError: object of type 'int' has no len()
```

It seems to happen no matter what I export, any ideas? Have I missed a step?

**Comment by 09th** [comment]
Seems that new uniforms appeared in new Blender versions. If you can send me example .blend file which cause this error I'll try to fix it.

**Comment by ScottDillman** [comment]
That would be great.. I put the file here: https://github.com/CTrauma/issue_files/blob/master/crate2.blend

**Comment by 09th** [comment]
Hmm, I have no error with this file, but in your case I see uniform types like 21, 22, 23 e.t.c., which should not normally appears. Are you use latest verion of B4P plugin to create *.jsd file?

**Comment by ScottDillman** [comment]
Just removed and reinstalled B4P and I get the same results.. maybe it is my Blender version:

Blender 2.74 (sub 4) System Information 

Blender:

version 2.74 (sub 4), branch b'master', commit date b'2015-04-07' b'01:25', hash b'9510137', b'Release'
build date: b'2015-04-07', b'05:28:22'
platform: b'Windows:64bit'

I uploaded the jsd file if you are interested

https://github.com/CTrauma/issue_files/blob/master/level.jsd

**Comment by 09th** [comment]
Ah, you use daily build. Ok, I can reproduce the problem with it, but can't find any information about new uniforms, so I need some time to investigate.  
For the time being you can use stable 2.74 release, which have no this problem.

**Comment by ScottDillman** [comment]
I build blender local from sources usually.. 
Thanks for looking at the problem.. I'll use stable for now..

**Comment by 09th** [comment]
Ok, updates pushed in both repo, plz, try with new version.

**Comment by ScottDillman** [comment]
Tried with new versions of both Blender4Panda-plugin and  YABEE and now if I try to 'export scene' I get the following:

Traceback (most recent call last):
  File ".config/blender/2.74/scripts/addons/Blender4Panda-plugin/operators.py", line 682, in execute
    e.invoke(export_dict, mat_dict, material, context, self.filepath, flags)
  File ".config/blender/2.74/scripts/addons/Blender4Panda-plugin/ext/base_shaders.py", line 299, in invoke
    saved_img = save_image(val, fname, all_data['scene']['paths']['images'])
KeyError: 'paths'

Is there somewhere I need to be defining my paths for output?

**Comment by 09th** [comment]
plz, check your jsd file, is it contain something like this?
        "paths": {
            "images": "res",
            "materials": "res",
            "meshes": "res",
            "sounds": "res"
        },

**Comment by ScottDillman** [comment]
I should probably move this conversation to the exporter, because I get the error on export not on loading of the scene and the exporter does not produce a jsd file because it fails before it writes the file.

**Comment by 09th** [comment]
Oh, sorry, I wasn't paying attention, that we are talking about the exporter. Seems I forgot to set the properly order of extensions invoking. Try next: open ext/base_scene.py and set order = 0.

**Comment by ScottDillman** [comment]
Works perfectly with that change THANKS! keep up the great work.
